name: dio_stage_host_selector
description: Stage Url and Proxy selector for Dio.
version: 2.1.2
author: Orteney
homepage: https://github.com/magdevelopment/DioStageHostSelector

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^4.0.0
  rxdart: ^0.27.0
  hive: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter