name: dio_stage_host_selector
description: Stage Url and Proxy selector for Dio.
version: 3.0.0
homepage: https://github.com/magdevelopment/DioStageHostSelector
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.0.0
  rxdart: ^0.27.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter